# This is a basic workflow to help you get started with Actions

name: release

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, release/*]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: info
        run: echo ${{ github.ref }}
      
      - name: checkout
        uses: actions/checkout@v2

      - name: install
        run: sudo apt-get install lua5.4
        
      - name: git
        run: |
          git config --global user.email "jkeane@gmail.com"
          git config --global user.name "Jonathan Keane"
                
      - name: test
        run: make test
        
      - name: bump
        run: make bump_build            
        
      - name: version
        run: echo "VERSION_TAG=v$(make sversion)" >> $GITHUB_ENV
        
      - name: tag
        run: | 
          git commit AnalogMetadata.lrdevplugin/Info.lua -m "Bump build ${{ env.VERSION_TAG }}"
          git tag ${{ env.VERSION_TAG }}
          git push --tags origin
          git push origin
                  
      - name: deliver
        run: make deliver
        
      - name: release
        id: release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: Release ${{ env.VERSION_TAG }}
          body: develop release
          draft: true
          prerelease: true
          
      - name: print_url
        run: echo "Release URL ${{ steps.release.html_url }}"
          
      - name: upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.release.outputs.upload_url }} # This pulls from the release step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./delivery/AnalogMetadata.lrplugin-${{ env.VERSION_TAG }}.zip
          asset_name: AnalogMetadata.lrplugin-${{ env.VERSION_TAG }}.zip
          asset_content_type: application/zip
          
          
        
      
        
        
      
